"""delete_unique_from_days_and_add_group_id_in_non_working_day_table

Revision ID: 2ca1e7d4efb9
Revises: f126f9407309
Create Date: 2026-10-03 15:47:33.191050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ca1e7d4efb9"
down_revision: str | Sequence[str] | None = "f126f9407309"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("non_working_day", sa.Column("group_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        op.f("non_working_day_day_key"), "non_working_day", type_="unique"
    )
    op.create_unique_constraint(
        "uq_non_working_day_day_group_id", "non_working_day", ["day", "group_id"]
    )
    op.create_foreign_key(
        "non_working_day_group_id_fkey",
        "non_working_day",
        "group",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "non_working_day_group_id_fkey", "non_working_day", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_non_working_day_day_group_id", "non_working_day", type_="unique"
    )
    op.create_unique_constraint(
        op.f("non_working_day_day_key"),
        "non_working_day",
        ["day"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("non_working_day", "group_id")
    # ### end Alembic commands ###
