"""add_student_settings_table

Revision ID: 758620702af4
Revises: 5195620dd930
Create Date: 2026-10-10 02:36:49.172368

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "758620702af4"
down_revision: str | Sequence[str] | None = "5195620dd930"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_settings",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("student_id"),
    )

    op.execute(
        sa.text("INSERT INTO student_settings (student_id) SELECT id FROM student;")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_settings")
    # ### end Alembic commands ###
