"""add_reminder_5min_column_in_student_settings

Revision ID: 8f434147523e
Revises: 758620702af4
Create Date: 2026-10-10 04:20:21.608325

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f434147523e"
down_revision: str | Sequence[str] | None = "758620702af4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_settings",
        sa.Column(
            "reminder_5min",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_settings", "reminder_5min")
    # ### end Alembic commands ###
