"""delete_surveys

Revision ID: 9ea913caf184
Revises: f2868f1090a4
Create Date: 2026-10-06 00:42:19.131833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ea913caf184"
down_revision: str | Sequence[str] | None = "f2868f1090a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_data")
    op.drop_table("survey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("survey_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student.id"], name=op.f("survey_data_student_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["survey_id"], ["survey.id"], name=op.f("survey_data_survey_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("survey_data_pkey")),
    )
    op.create_table(
        "survey",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("survey_pkey")),
    )
    # ### end Alembic commands ###
