"""add_unique_constraint_to_class

Revision ID: f126f9407309
Revises: a2c67d667543
Create Date: 2026-09-30 14:50:18.265489

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f126f9407309"
down_revision: str | Sequence[str] | None = "a2c67d667543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_class_start_at_end_at", "class", ["start_at", "end_at"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_class_start_at_end_at", "class", type_="unique")
    # ### end Alembic commands ###
