"""class_type_id_and_audience_id_to_nullable

Revision ID: f2868f1090a4
Revises: 2ca1e7d4efb9
Create Date: 2026-10-04 00:17:25.206960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2868f1090a4"
down_revision: str | Sequence[str] | None = "2ca1e7d4efb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "replacement_schedule",
        "class_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "replacement_schedule", "audience_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "schedule", "class_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "schedule", "audience_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule", "audience_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "schedule", "class_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "replacement_schedule",
        "audience_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "replacement_schedule",
        "class_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
